### ISSUE TITLE
/v3/segments 有没有好的方法

### ISSUE THREAD

**Issue by chenxu-javascript** [SkyAPMTest/skywalking-client-test#15]
![image](https://user-images.githubusercontent.com/16332458/122525176-8d7f8000-d04b-11eb-9736-2a36dea5e164.png)
![image](https://user-images.githubusercontent.com/16332458/122525219-9a9c6f00-d04b-11eb-881a-ad8a1122d69c.png)

**Comment by wu-sheng** [comment]
This is only a test repo.
